// Main Application Entry Point (ES Module)

import { SCRIPT_URL, DEBUG } from './config.js';
import { safeGet, safeSet, safeRemove } from './storage.js';
import {
  escapeHtml,
  sanitizeUrl,
  formatUserErrorMessage,
  showToast,
  showInfoModal,
  closeConfirmModal,
  showConfirmModal,
  showView,
  formatIDR,
  formatRupiah,
  formatTime,
  formatDate,
  formatCompactDate,
  formatInputRibuan,
  parseRibuan,
  statusBadge,
  paymentStatusIcon,
  actionArrowIcon,
  renderOptimizedImage
} from './utils.js';
import {
  startViewTiming,
  markFetchStart,
  markFetchEnd,
  markRenderStart,
  markRenderEnd,
  endViewTiming,
  getRoleMetrics,
  getAllRoleMetrics,
  resetMetrics,
  checkPerformanceBudget,
  ROLE_PERFORMANCE_BUDGETS
} from './perf.js';
import { fetchBackend, run, callQueued, call } from './api.js';
import { appState, initTargetCampaignId, currentToken, currentRole, currentUser } from './state.js';
import {
  resetUserLoginForm,
  cancelUserLogin,
  userLogin,
  logoutUser,
  logoutToken,
  loginToken,
  deepDive,
  returnFromDeepDive,
  tokenLogin,
  cancelPicCreate,
  seamlessLoginAsPic,
  returnToMemberDashboard,
  updateTabTitle,
  playAlertChime,
  startAdminPolling
} from './views/auth.js';
import {
  openProfileModal,
  closeProfileModal,
  saveProfile,
  loadUserDashboard,
  seamlessBecomePic,
  sortCampaignsForDonorDashboard,
  refreshCampaignList,
  clearTargetCampaign,
  toggleSelectAllBulkJoin,
  updateBulkJoinBtnVisibility,
  openBulkJoinModal,
  toggleBulkJoinFields,
  submitBulkJoin,
  getDeadlineBadge,
  copyAmount,
  renderCombinedCampaignCard,
  renderCampaignCard,
  joinCampaign,
  toggleCustomAmount,
  withdraw,
  submitProof,
  submitCombinedProof,
  deleteDraftCampaign
} from './views/donor.js';
import {
  loadPicDashboard,
  createCampaign,
  getPicProgress,
  isVisiblePicActionTarget,
  scrollToPicActions,
  scrollToPicDonorAction,
  renderPicActionItem,
  renderPicActionQueue,
  renderPicNextAction,
  renderPicDashboard,
  renderPicActions,
  showLateDonorForm,
  hideLateDonorForm,
  toggleLateCustomAmount,
  showGiftProofForm,
  submitGiftProof,
  submitLateDonor,
  copyShareLink,
  copyPicGroupReminder,
  closeList,
  reopenList,
  archiveThis,
  deleteThis,
  renderAndShow,
  showFinalizeForm,
  doFinalize,
  getPicDonorQueueState,
  getPicDonorQueueLabel,
  renderDonorTable,
  copyUnpaidDonorsRecap,
  copyBulkMessage,
  verifyPaymentUI,
  picVerifyAllUI,
  markRefundedUI,
  copyLaporanSelesai
} from './views/pic.js';
import {
  renderSummaryCard,
  refreshSummary,
  resetAdminActionQueue,
  updateAdminActionQueue,
  loadAdminDashboard,
  getAdminParentCard,
  refreshPendingMembers,
  scrollToPending,
  approvePending,
  toggleSelectAllPending,
  bulkApprovePending,
  refreshLateRequests,
  handleApproveLateDonor,
  executeApproveLateDonor,
  refreshAdmins,
  adminFilterText,
  filterAdminItems,
  filterAdminCampaigns,
  filterAdminAccounts,
  renderAdminAccounts,
  revokeAdmin,
  deleteAdmin,
  reactivateAdmin,
  genPicToken,
  refreshAdminCampaigns,
  renderAdminCampaignDeadline,
  renderAdminCampaignActions,
  renderAdminCampaignViews,
  adminView,
  adminRecalculateUI,
  adminTransferOwnershipUI,
  closeEditGiftModal,
  adminEditGiftAmountUI,
  adminDeleteDonorUI,
  adminTogglePaidUI,
  closeEditAmountModal,
  editAmountPaid,
  adminArchive,
  adminDelete,
  loadMoreMembers,
  filterMembers,
  refreshMembers,
  renderMemberStatusControl,
  renderMemberActions,
  renderMembersView,
  renderMembersHtml,
  updateMemberStatusUI,
  assignMemberRoleUI,
  addMemberUI,
  removeMemberUI,
  refreshSACampaigns
} from './views/admin.js';
import {
  loadSuperAdminDashboard,
  runDataSweep,
  saveSettings,
  genAdminToken
} from './views/superadmin.js';

// Expose all functions on window for inline HTML onclick/onchange/onkeyup and global tests
const globalBindings = {
  SCRIPT_URL,
  DEBUG,
  safeGet,
  safeSet,
  safeRemove,
  escapeHtml,
  sanitizeUrl,
  formatUserErrorMessage,
  showToast,
  showInfoModal,
  closeConfirmModal,
  showConfirmModal,
  showView,
  formatIDR,
  formatRupiah,
  formatTime,
  formatDate,
  formatCompactDate,
  formatInputRibuan,
  parseRibuan,
  statusBadge,
  paymentStatusIcon,
  actionArrowIcon,
  renderOptimizedImage,
  fetchBackend,
  run,
  callQueued,
  call,
  appState,
  initTargetCampaignId,
  currentToken,
  currentRole,
  currentUser,
  resetUserLoginForm,
  cancelUserLogin,
  userLogin,
  logoutUser,
  logoutToken,
  loginToken,
  deepDive,
  returnFromDeepDive,
  tokenLogin,
  cancelPicCreate,
  seamlessLoginAsPic,
  returnToMemberDashboard,
  updateTabTitle,
  playAlertChime,
  startAdminPolling,
  openProfileModal,
  closeProfileModal,
  saveProfile,
  loadUserDashboard,
  seamlessBecomePic,
  sortCampaignsForDonorDashboard,
  refreshCampaignList,
  clearTargetCampaign,
  toggleSelectAllBulkJoin,
  updateBulkJoinBtnVisibility,
  openBulkJoinModal,
  toggleBulkJoinFields,
  submitBulkJoin,
  getDeadlineBadge,
  copyAmount,
  renderCombinedCampaignCard,
  renderCampaignCard,
  joinCampaign,
  toggleCustomAmount,
  withdraw,
  submitProof,
  submitCombinedProof,
  deleteDraftCampaign,
  loadPicDashboard,
  createCampaign,
  getPicProgress,
  isVisiblePicActionTarget,
  scrollToPicActions,
  scrollToPicDonorAction,
  renderPicActionItem,
  renderPicActionQueue,
  renderPicNextAction,
  renderPicDashboard,
  renderPicActions,
  showLateDonorForm,
  hideLateDonorForm,
  toggleLateCustomAmount,
  showGiftProofForm,
  submitGiftProof,
  submitLateDonor,
  copyShareLink,
  copyPicGroupReminder,
  closeList,
  reopenList,
  archiveThis,
  deleteThis,
  renderAndShow,
  showFinalizeForm,
  doFinalize,
  getPicDonorQueueState,
  getPicDonorQueueLabel,
  renderDonorTable,
  copyUnpaidDonorsRecap,
  copyBulkMessage,
  verifyPaymentUI,
  picVerifyAllUI,
  markRefundedUI,
  copyLaporanSelesai,
  renderSummaryCard,
  refreshSummary,
  resetAdminActionQueue,
  updateAdminActionQueue,
  loadAdminDashboard,
  getAdminParentCard,
  refreshPendingMembers,
  scrollToPending,
  approvePending,
  toggleSelectAllPending,
  bulkApprovePending,
  refreshLateRequests,
  handleApproveLateDonor,
  executeApproveLateDonor,
  refreshAdmins,
  adminFilterText,
  filterAdminItems,
  filterAdminCampaigns,
  filterAdminAccounts,
  renderAdminAccounts,
  revokeAdmin,
  deleteAdmin,
  reactivateAdmin,
  genPicToken,
  refreshAdminCampaigns,
  renderAdminCampaignDeadline,
  renderAdminCampaignActions,
  renderAdminCampaignViews,
  adminView,
  adminRecalculateUI,
  adminTransferOwnershipUI,
  closeEditGiftModal,
  adminEditGiftAmountUI,
  adminDeleteDonorUI,
  adminTogglePaidUI,
  closeEditAmountModal,
  editAmountPaid,
  adminArchive,
  adminDelete,
  loadMoreMembers,
  filterMembers,
  refreshMembers,
  renderMemberStatusControl,
  renderMemberActions,
  renderMembersView,
  renderMembersHtml,
  updateMemberStatusUI,
  assignMemberRoleUI,
  addMemberUI,
  removeMemberUI,
  refreshSACampaigns,
  loadSuperAdminDashboard,
  runDataSweep,
  saveSettings,
  genAdminToken,
  startViewTiming,
  markFetchStart,
  markFetchEnd,
  markRenderStart,
  markRenderEnd,
  endViewTiming,
  getRoleMetrics,
  getAllRoleMetrics,
  resetMetrics,
  checkPerformanceBudget,
  ROLE_PERFORMANCE_BUDGETS
};

if (typeof window !== 'undefined') {
  Object.assign(window, globalBindings);
}

export function initApp() {
  initTargetCampaignId();

  const user = safeGet('donor_user');
  const token = safeGet('auth_token');
  const role = safeGet('auth_role');

  if (token && role) {
    if (role === 'PIC') loadPicDashboard();
    else if (role === 'Admin') loadAdminDashboard();
    else if (role === 'SuperAdmin') loadSuperAdminDashboard();
  } else if (user) {
    loadUserDashboard();
  } else {
    showView('landing');
  }

  // Initialize Flatpickr for date inputs if available
  if (typeof flatpickr !== 'undefined') {
    const maxD = new Date();
    maxD.setMonth(maxD.getMonth() + 2);

    flatpickr("input[type='date']", {
      dateFormat: "Y-m-d",
      allowInput: true,
      disableMobile: "true",
      minDate: "today",
      maxDate: maxD
    });
  }
}

if (typeof document !== 'undefined') {
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initApp);
  } else {
    initApp();
  }
}

export default globalBindings;
