/**
 * Donatur Helper - Static Frontend Build Script
 * File: scripts/deployment/build-static.cjs
 *
 * Description:
 * Prepares the Donatur Helper static frontend for deployment on Cloudflare Pages.
 * - Injects environment variables into js/config/env.local.js
 * - Validates required Supabase credentials in CI/production
 * - Cleans and populates the dist/ output directory with only static assets
 * - Excludes server-side files, databases, tests, documentation, and secrets
 */

const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

// Project root directory
const ROOT_DIR = path.resolve(__dirname, '..', '..');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const LOCAL_CONFIG_DIR = path.join(ROOT_DIR, 'js', 'config');
const LOCAL_ENV_PATH = path.join(LOCAL_CONFIG_DIR, 'env.local.js');

// Root static files allowed in dist
const ROOT_STATIC_FILES = [
  'index.html',
  '_headers',
  'robots.txt',
  'manifest.json',
  'favicon.ico'
];

// Directories allowed in dist
const STATIC_DIRECTORIES = [
  'css',
  'js',
  'assets',
  'images',
  'favicon'
];

// Explicit exclusions to safeguard against leaking non-frontend assets
const EXCLUDE_NAMES = new Set([
  '.git',
  '.github',
  '.agent',
  '.agents',
  '.claude',
  '.scratch',
  '.worktrees',
  '.wrangler',
  '.netlify',
  'node_modules',
  'docs',
  'reports',
  'supabase',
  'scripts',
  'tests',
  'data',
  'legacy',
  'secrets',
  'package.json',
  'package-lock.json',
  'appsscript.json',
  'Code.js',
  'deno.lock',
  '.env',
  '.env.local',
  '.env.production',
  '.env.cloudflare',
  '.clasp.json',
  '.claspignore',
  '.cloudflareignore',
  'netlify.toml',
  'netlify_index.html',
  'nlp_auditor.py',
  'build-dist.js'
]);

/**
 * Helper to parse boolean from environment string
 * @param {*} val
 * @param {boolean} defaultVal
 * @returns {boolean}
 */
function parseBoolean(val, defaultVal) {
  if (val === undefined || val === null || val === '') return defaultVal;
  if (typeof val === 'boolean') return val;
  const str = String(val).trim().toLowerCase();
  if (str === 'true' || str === '1' || str === 'yes') return true;
  if (str === 'false' || str === '0' || str === 'no') return false;
  return defaultVal;
}

/**
 * Generates js/config/env.local.js file contents with exact required shape
 * @param {Object} env
 * @returns {string}
 */
function formatEnvLocalJs(env) {
  return `/**
 * Donatur Helper - Environment Configuration (Generated)
 * Generated by scripts/deployment/build-static.cjs
 */

window.__DH_ENV__ = {
  SUPABASE_URL: ${JSON.stringify(env.SUPABASE_URL)},
  SUPABASE_PUBLISHABLE_KEY: ${JSON.stringify(env.SUPABASE_PUBLISHABLE_KEY)},
  BACKEND_MODE: ${JSON.stringify(env.BACKEND_MODE)},
  ALLOW_GAS_FALLBACK: ${env.ALLOW_GAS_FALLBACK ? 'true' : 'false'},
  DEBUG: ${env.DEBUG ? 'true' : 'false'},
  GAS_ENDPOINT: ${JSON.stringify(env.GAS_ENDPOINT)}
};
`;
}

/**
 * Recursively copies a directory to destination with exclusion filtering
 * @param {string} srcDir
 * @param {string} destDir
 * @returns {{ filesCopied: number, dirsCopied: number }}
 */
function copyDirFiltered(srcDir, destDir) {
  fs.mkdirSync(destDir, { recursive: true });
  let filesCopied = 0;
  let dirsCopied = 1;

  const entries = fs.readdirSync(srcDir, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);

    if (EXCLUDE_NAMES.has(entry.name)) {
      continue;
    }
    if (entry.name.startsWith('.') && entry.name !== '_headers') {
      continue;
    }

    if (entry.isDirectory()) {
      const sub = copyDirFiltered(srcPath, destPath);
      filesCopied += sub.filesCopied;
      dirsCopied += sub.dirsCopied;
    } else if (entry.isFile()) {
      fs.copyFileSync(srcPath, destPath);
      filesCopied += 1;
    }
  }

  return { filesCopied, dirsCopied };
}

/**
 * Main build execution function
 */
function build() {
  const isProduction = Boolean(process.env.CF_PAGES || process.env.CI);
  const buildModeLabel = isProduction ? 'Production (Cloudflare Pages / CI)' : 'Local';

  console.log(`[Build] Starting Donatur Helper static build in ${buildModeLabel} mode...`);

  let envConfig = null;
  let envFileContent = null;
  let usingExistingLocalConfig = false;

  const envSupabaseUrl = process.env.SUPABASE_URL ? process.env.SUPABASE_URL.trim() : '';
  const envSupabaseKey = process.env.SUPABASE_PUBLISHABLE_KEY ? process.env.SUPABASE_PUBLISHABLE_KEY.trim() : '';

  if (isProduction) {
    // Production Mode: Require credentials
    const missingVars = [];
    if (!envSupabaseUrl) missingVars.push('SUPABASE_URL');
    if (!envSupabaseKey) missingVars.push('SUPABASE_PUBLISHABLE_KEY');

    if (missingVars.length > 0) {
      console.error(`[Build Error] Production build failed: Missing required environment variable(s): ${missingVars.join(', ')}`);
      console.error('Please configure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY in your Cloudflare Pages project settings.');
      process.exit(1);
    }

    envConfig = {
      SUPABASE_URL: envSupabaseUrl,
      SUPABASE_PUBLISHABLE_KEY: envSupabaseKey,
      BACKEND_MODE: process.env.DH_BACKEND_MODE ? process.env.DH_BACKEND_MODE.trim() : 'auto',
      ALLOW_GAS_FALLBACK: parseBoolean(process.env.DH_ALLOW_GAS_FALLBACK, true),
      DEBUG: parseBoolean(process.env.DH_DEBUG, false),
      GAS_ENDPOINT: process.env.DH_GAS_ENDPOINT ? process.env.DH_GAS_ENDPOINT.trim() : ''
    };
    envFileContent = formatEnvLocalJs(envConfig);

  } else {
    // Local Build Mode
    if (envSupabaseUrl && envSupabaseKey) {
      envConfig = {
        SUPABASE_URL: envSupabaseUrl,
        SUPABASE_PUBLISHABLE_KEY: envSupabaseKey,
        BACKEND_MODE: process.env.DH_BACKEND_MODE ? process.env.DH_BACKEND_MODE.trim() : 'auto',
        ALLOW_GAS_FALLBACK: parseBoolean(process.env.DH_ALLOW_GAS_FALLBACK, true),
        DEBUG: parseBoolean(process.env.DH_DEBUG, false),
        GAS_ENDPOINT: process.env.DH_GAS_ENDPOINT ? process.env.DH_GAS_ENDPOINT.trim() : ''
      };
      envFileContent = formatEnvLocalJs(envConfig);
    } else if (fs.existsSync(LOCAL_ENV_PATH)) {
      console.warn('[Build Warning] Using existing local env.local.js. Do not use this behavior in production.');
      usingExistingLocalConfig = true;
      envFileContent = fs.readFileSync(LOCAL_ENV_PATH, 'utf8');

      // Safely parse summary metadata from existing file
      try {
        const sandbox = { window: {} };
        vm.runInNewContext(envFileContent, sandbox);
        const parsed = sandbox.window.__DH_ENV__ || {};
        envConfig = {
          BACKEND_MODE: parsed.BACKEND_MODE || 'auto',
          ALLOW_GAS_FALLBACK: parsed.ALLOW_GAS_FALLBACK !== undefined ? Boolean(parsed.ALLOW_GAS_FALLBACK) : true,
          DEBUG: parsed.DEBUG !== undefined ? Boolean(parsed.DEBUG) : false
        };
      } catch {
        envConfig = {
          BACKEND_MODE: 'auto',
          ALLOW_GAS_FALLBACK: true,
          DEBUG: false
        };
      }
    } else {
      console.error('[Build Error] Local build failed: Missing required environment variables (SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY) and no existing js/config/env.local.js found.');
      console.error('Either provide environment variables or copy js/config/env.example.js to js/config/env.local.js.');
      process.exit(1);
    }
  }

  // Clean and recreate dist directory
  if (fs.existsSync(DIST_DIR)) {
    fs.rmSync(DIST_DIR, { recursive: true, force: true });
  }
  fs.mkdirSync(DIST_DIR, { recursive: true });

  let totalFilesCopied = 0;
  let totalDirsCopied = 0;

  // Copy Root Static Files
  for (const filename of ROOT_STATIC_FILES) {
    const srcPath = path.join(ROOT_DIR, filename);
    if (fs.existsSync(srcPath) && fs.statSync(srcPath).isFile()) {
      const destPath = path.join(DIST_DIR, filename);
      fs.copyFileSync(srcPath, destPath);
      totalFilesCopied += 1;
    }
  }

  // Copy Static Directories
  for (const dirName of STATIC_DIRECTORIES) {
    const srcDirPath = path.join(ROOT_DIR, dirName);
    if (fs.existsSync(srcDirPath) && fs.statSync(srcDirPath).isDirectory()) {
      const destDirPath = path.join(DIST_DIR, dirName);
      const res = copyDirFiltered(srcDirPath, destDirPath);
      totalFilesCopied += res.filesCopied;
      totalDirsCopied += res.dirsCopied;
    }
  }

  // Ensure generated or existing env.local.js is placed in dist/js/config/env.local.js
  const distConfigDir = path.join(DIST_DIR, 'js', 'config');
  fs.mkdirSync(distConfigDir, { recursive: true });
  const distEnvPath = path.join(distConfigDir, 'env.local.js');

  if (envFileContent) {
    fs.writeFileSync(distEnvPath, envFileContent, 'utf8');
  }

  // Verify that dist/js/config/env.local.js exists
  if (!fs.existsSync(distEnvPath)) {
    console.error('[Build Error] Failed to create dist/js/config/env.local.js');
    process.exit(1);
  }

  // Print Safe Build Summary (NO SECRETS, NO KEYS, NO GAS_ENDPOINT)
  console.log('\n==================================================');
  console.log('  Donatur Helper - Static Build Complete');
  console.log('==================================================');
  console.log(`  Build Mode:          ${buildModeLabel}`);
  console.log(`  Dist Output Path:    ${DIST_DIR}`);
  console.log(`  Copied Assets:       ${totalFilesCopied} file(s), ${totalDirsCopied} folder(s)`);
  console.log(`  Backend Mode:        ${envConfig ? envConfig.BACKEND_MODE : 'unknown'}`);
  console.log(`  Allow GAS Fallback:  ${envConfig ? envConfig.ALLOW_GAS_FALLBACK : 'unknown'}`);
  console.log(`  Debug Mode:          ${envConfig ? envConfig.DEBUG : 'unknown'}`);
  console.log('==================================================\n');
}

if (require.main === module) {
  build();
}

module.exports = {
  build,
  parseBoolean,
  formatEnvLocalJs,
  copyDirFiltered,
  ROOT_STATIC_FILES,
  STATIC_DIRECTORIES,
  EXCLUDE_NAMES
};
